// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: message_service_v1.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MessageService_RealtimeConversation_FullMethodName = "/message.MessageService/RealtimeConversation"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	// *
	// RealtimeConversation
	// リアルタイムにAIと会話をするためのリクエストとレスポンスを行うストリーミングRPCです。
	RealtimeConversation(ctx context.Context, opts ...grpc.CallOption) (MessageService_RealtimeConversationClient, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) RealtimeConversation(ctx context.Context, opts ...grpc.CallOption) (MessageService_RealtimeConversationClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], MessageService_RealtimeConversation_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceRealtimeConversationClient{stream}
	return x, nil
}

type MessageService_RealtimeConversationClient interface {
	Send(*RealtimeConversationRequest) error
	Recv() (*RealtimeConversationResponse, error)
	grpc.ClientStream
}

type messageServiceRealtimeConversationClient struct {
	grpc.ClientStream
}

func (x *messageServiceRealtimeConversationClient) Send(m *RealtimeConversationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServiceRealtimeConversationClient) Recv() (*RealtimeConversationResponse, error) {
	m := new(RealtimeConversationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations should embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	// *
	// RealtimeConversation
	// リアルタイムにAIと会話をするためのリクエストとレスポンスを行うストリーミングRPCです。
	RealtimeConversation(MessageService_RealtimeConversationServer) error
}

// UnimplementedMessageServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) RealtimeConversation(MessageService_RealtimeConversationServer) error {
	return status.Errorf(codes.Unimplemented, "method RealtimeConversation not implemented")
}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_RealtimeConversation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServiceServer).RealtimeConversation(&messageServiceRealtimeConversationServer{stream})
}

type MessageService_RealtimeConversationServer interface {
	Send(*RealtimeConversationResponse) error
	Recv() (*RealtimeConversationRequest, error)
	grpc.ServerStream
}

type messageServiceRealtimeConversationServer struct {
	grpc.ServerStream
}

func (x *messageServiceRealtimeConversationServer) Send(m *RealtimeConversationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServiceRealtimeConversationServer) Recv() (*RealtimeConversationRequest, error) {
	m := new(RealtimeConversationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RealtimeConversation",
			Handler:       _MessageService_RealtimeConversation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message_service_v1.proto",
}
