// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: message_service_v1.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RealtimeConversationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// Message
	// メッセージ(ユーザ)
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RealtimeConversationRequest) Reset() {
	*x = RealtimeConversationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_service_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealtimeConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeConversationRequest) ProtoMessage() {}

func (x *RealtimeConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_service_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeConversationRequest.ProtoReflect.Descriptor instead.
func (*RealtimeConversationRequest) Descriptor() ([]byte, []int) {
	return file_message_service_v1_proto_rawDescGZIP(), []int{0}
}

func (x *RealtimeConversationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RealtimeConversationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// MessageID
	// メッセージのID (1文字ずつではなく、1つのメッセージで一意)
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// *
	// MessageChar
	// メッセージ1文字(AI)
	MessageChar string `protobuf:"bytes,2,opt,name=message_char,json=messageChar,proto3" json:"message_char,omitempty"`
	// *
	// IsDone
	// 完了済みかどうか
	// 1つのメッセージのストリームが完了したかどうかを表します。
	IsDone bool `protobuf:"varint,3,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
}

func (x *RealtimeConversationResponse) Reset() {
	*x = RealtimeConversationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_service_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealtimeConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeConversationResponse) ProtoMessage() {}

func (x *RealtimeConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_service_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeConversationResponse.ProtoReflect.Descriptor instead.
func (*RealtimeConversationResponse) Descriptor() ([]byte, []int) {
	return file_message_service_v1_proto_rawDescGZIP(), []int{1}
}

func (x *RealtimeConversationResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RealtimeConversationResponse) GetMessageChar() string {
	if x != nil {
		return x.MessageChar
	}
	return ""
}

func (x *RealtimeConversationResponse) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

var File_message_service_v1_proto protoreflect.FileDescriptor

var file_message_service_v1_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x1b, 0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x43,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x79, 0x0a, 0x1c,
	0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x73, 0x5f, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x32, 0x79, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x14, 0x52, 0x65, 0x61,
	0x6c, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x24, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x6c,
	0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_service_v1_proto_rawDescOnce sync.Once
	file_message_service_v1_proto_rawDescData = file_message_service_v1_proto_rawDesc
)

func file_message_service_v1_proto_rawDescGZIP() []byte {
	file_message_service_v1_proto_rawDescOnce.Do(func() {
		file_message_service_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_service_v1_proto_rawDescData)
	})
	return file_message_service_v1_proto_rawDescData
}

var file_message_service_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_service_v1_proto_goTypes = []interface{}{
	(*RealtimeConversationRequest)(nil),  // 0: message.RealtimeConversationRequest
	(*RealtimeConversationResponse)(nil), // 1: message.RealtimeConversationResponse
}
var file_message_service_v1_proto_depIdxs = []int32{
	0, // 0: message.MessageService.RealtimeConversation:input_type -> message.RealtimeConversationRequest
	1, // 1: message.MessageService.RealtimeConversation:output_type -> message.RealtimeConversationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_service_v1_proto_init() }
func file_message_service_v1_proto_init() {
	if File_message_service_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_service_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealtimeConversationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_service_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealtimeConversationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_service_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_service_v1_proto_goTypes,
		DependencyIndexes: file_message_service_v1_proto_depIdxs,
		MessageInfos:      file_message_service_v1_proto_msgTypes,
	}.Build()
	File_message_service_v1_proto = out.File
	file_message_service_v1_proto_rawDesc = nil
	file_message_service_v1_proto_goTypes = nil
	file_message_service_v1_proto_depIdxs = nil
}
